install packages in two waves

diff --git a/software/Dockerfile b/software/Dockerfile
--- a/software/Dockerfile
+++ b/software/Dockerfile
@@ -49,7 +49,10 @@ COPY ./renv.lock ./renv.lock
 ENV RENV_PATHS_RENV=/app/renv
 ENV RENV_PATHS_LOCKFILE=/app/renv.lock
 
-RUN R --no-echo -e "options(Ncpus = 1); renv::restore(clean = TRUE)" \
+# Parallel dependencies processing in renv cause errors because of unordered transitive dependencies installation
+# We have to run restoration process twice: first wave installs most of deps, 2nd wave fixes failures from races
+RUN R --no-echo -e "renv::restore(clean = TRUE)" || true
+RUN R --no-echo -e "renv::restore()" \
     && find /root/.cache/R -name keys.html -delete \
     && find /usr/local/lib/R -name keys.html -delete
 
